<a href="https://colab.research.google.com/github/insoucyant/Learn_Python/blob/master/1Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np
# !pip list

# Tensors
* A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
* Similar to Mumpy Arrays but work better on GPU's
* Default data type is float 32
* More suitable for Deep Learning than numpy array

In [5]:
np1 =np.random.rand(3,4)
print(np1)
tensor_2d = torch.randn(3,4)
print(tensor_2d)

[[0.48114272 0.55795585 0.36081817 0.24105977]
 [0.59890793 0.90067098 0.05022431 0.85851084]
 [0.29493922 0.42776972 0.50431674 0.87331629]]
tensor([[-0.7676, -0.1191, -0.3618,  0.5415],
        [-2.7378, -0.4467,  2.2242,  1.4048],
        [ 0.9756, -0.1512, -1.5466,  0.8078]])
