<a href="https://colab.research.google.com/github/insoucyant/Learn_Python/blob/master/TorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch is a deep learning framework and scientific computing package. The scientific computing aspect of PyTorch is primarily a result of PyTroch's tensor libraray and associated Tensor operations.

In [ ]:
import torch
import numpy as np
# !pip list

# Tensors
* Tensors are the data structure of Deep Learning. The primary datastructure in PyTorch is torch.Tensor
* Tensor is a multi-dimensional matrix (n-dimensional array) containing elements of a single data type.
* Similar to Numpy Arrays but work better on GPU's
* Default data type is float 32
* More suitable for Deep Learning than numpy array
* Keywords: arange, reshape, view, randn

# Torch
Torch is the core library and namespace that provide the fundamental building blocks for deep learning.  
torch is the low level foundation upon which the higher level components of PyTorch, such as torch.nn (for neural network layers) and torch.optim (for optimizers), are built
The main torch libraries/subpackages are:
* *torch.nn* : &emsp; This subpackage provides modules for building neural network including
* *torch.autograd* : &emsp;      **Automatic Differentiation**, automatically computes gradients for all operations on tensors.
* *torch.nn.functional* : &emsp;
* *torch.optim* : &emsp;
* *torch.utils* : &emsp;
* *torchvision* : &emsp;

In [ ]:
np1 =np.random.rand(3,4)
print(np1)
print(f'The Numpy data type is {np1.dtype}')
tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(f'The Numpy data type is {tensor_2d.dtype}')


[[0.21303738 0.77657514 0.64104747 0.92779252]
 [0.25132811 0.5568206  0.39733164 0.80141154]
 [0.30793448 0.81171191 0.89547938 0.68055691]]
The Numpy data type is float64
tensor([[ 0.6623,  0.3676,  1.2984, -0.2266],
        [-0.0864, -2.4531, -0.2122, -0.2220],
        [ 0.8590, -1.8581, -0.4010,  0.5967]])
The Numpy data type is torch.float32


In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create Tensor out of numpy array
my_tensor = torch.tensor(np1)
print(f'This tensors data type is {tensor_2d.dtype}')
my_tensor

This tensors data type is torch.float32


tensor([[0.2130, 0.7766, 0.6410, 0.9278],
        [0.2513, 0.5568, 0.3973, 0.8014],
        [0.3079, 0.8117, 0.8955, 0.6806]], dtype=torch.float64)

What is the difference between reshape and view in pytorch?

In [ ]:
# Arange, reshape, view
my_torch = torch.arange(10)
print(my_torch)
my_torch = my_torch.reshape(2,5)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
# Reshape if we do not know number of elements
my_torch2 = torch.arange(10)
print(my_torch2)
my_torch2 = my_torch2.reshape(-1,5)
print(my_torch2)
my_torch2 = my_torch2.reshape(5,-1)
print(my_torch2)
# my_torch2 = my_torch2.reshape(3,-1)
# print(my_torch2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
print(my_torch5)
print(my_torch6)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
my_torch5[1] = 9999
print(my_torch5)
print(my_torch6)
my_torch3[1] = 7777
print(my_torch3)
print(my_torch4)

tensor([   0, 9999,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 9999,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([   0, 7777,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 7777,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


Bot view and reshape refelct the change at the source

#### Slicing

In [ ]:
my_torch7 = torch.arange(10)
print(my_torch7[7])
my_torch8 = my_torch7.reshape(5,2)
print(my_torch8[:,1])
# Return teh column and keep the shape
print(my_torch8[:,1:])

tensor(7)
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])


# Tensor Math Operations
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and Longhand
* Reassignment

# Reference
* https://deeplizard.com/learn/video/iTKbyFh-7GM